openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 6.6.6
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /beers:
    get:
      summary: Returns a list of beers.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of beers
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: Creates a new beer as a resource
      description: Cold one or warm one, doesn't matter - the best beer is a beer after work
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                beer:
                  type: string
                volume:
                  type: number
                isGood:
                  type: boolean
      responses:
        '201':    # status code
          description: Created a resource of beer
        '400': 
          description: Wrong query you moron!
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string